GOOGLE_CLOUD_PROJECT_NAME_BASE := moov
GOOGLE_CLOUD_REGION ?= europe-west1
GOOGLE_CLOUD_DOCKER_REGISTRY ?= $(GOOGLE_CLOUD_REGION)-docker.pkg.dev

DEV_GOOGLE_CLOUD_PROJECT_NAME   ?= $(GOOGLE_CLOUD_PROJECT_NAME_BASE)-dev
DEV_GOOGLE_CLOUD_PROJECT_ID     ?= $(DEV_GOOGLE_CLOUD_PROJECT_NAME)-439608
DEV_GOOGLE_CLOUD_PROJECT_NUMBER ?= 203475703228

STAGING_GOOGLE_CLOUD_PROJECT_NAME   ?= $(GOOGLE_CLOUD_PROJECT_NAME_BASE)-staging
STAGING_GOOGLE_CLOUD_PROJECT_ID     ?= $(STAGING_GOOGLE_CLOUD_PROJECT_NAME)-440506
STAGING_GOOGLE_CLOUD_PROJECT_NUMBER ?= 326118600145

PROD_GOOGLE_CLOUD_PROJECT_NAME   ?= $(GOOGLE_CLOUD_PROJECT_NAME_BASE)
PROD_GOOGLE_CLOUD_PROJECT_ID     ?= $(PROD_GOOGLE_CLOUD_PROJECT_NAME)-438615
PROD_GOOGLE_CLOUD_PROJECT_NUMBER ?= 378762893981
