services:
  nestor:
    image: ${VEGITO_LOCAL_PUBLIC_IMAGES_BASE_NAME}:nestor-latest
    environment:
      VEGITO_DOCKER_DEBIAN_DESKTOP_X_GPU_MODE: wayland
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      LOCAL_WORKSPACE: ${PWD}
      DOCKER_HOST: "unix:///run/user/1000/docker.sock"
      ROOT_DOCKER_HOST: "unix:///var/run/docker.sock"
      LOCAL_NESTOR_OLLAMA: ollama
    runtime: nvidia
    devices:
      - /dev/nvidia0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    working_dir: ${PWD}
    shm_size: "8gb"
    ports:
      # Xpra
      - "5901"
      # Docker DIND as localhost:2976 using localproxy
      - "2976"
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - ${LOCAL_WORKSPACE:-${PWD}}:${PWD}:cached
      # Shared volumes for Ollama models and cache
      - ${AI_WORKSPACES:-/workspaces/ai}:/workspaces/ai:rw
      # Docker socket for external Docker control
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

    networks:
      ai:
        aliases:
          - ai-nestor-nestor
networks:
  ai-nestor:
    name: ai-nestor
