title = "Vegito Gitleaks Config"
description = "Allowlist Vegito non-sensitive files"
version = 2

[allowlist]
description = "Global allowlist for non-sensitive files"
paths = [
  ".*terraform\\.tfstate",
  ".*\\.devcontainer/genieai\\.chatgpt-vscode.*",
]
regexes = [
  "AIza[0-9A-Za-z\\-_]{35}",
]