GOOGLE_CLOUD_PROJECT_NAME_BASE := moov

INFRA_ENV ?= dev

DEV_GOOGLE_CLOUD_PROJECT_NAME   ?= $(GOOGLE_CLOUD_PROJECT_NAME_BASE)-dev
DEV_GOOGLE_CLOUD_PROJECT_ID     ?= $(DEV_GOOGLE_CLOUD_PROJECT_NAME)-439608
DEV_GOOGLE_CLOUD_PROJECT_NUMBER ?= 203475703228

STAGING_GOOGLE_CLOUD_PROJECT_NAME   ?= $(GOOGLE_CLOUD_PROJECT_NAME_BASE)-staging
STAGING_GOOGLE_CLOUD_PROJECT_ID     ?= $(STAGING_GOOGLE_CLOUD_PROJECT_NAME)-440506
STAGING_GOOGLE_CLOUD_PROJECT_NUMBER ?= 326118600145

PROD_GOOGLE_CLOUD_PROJECT_NAME   ?= $(GOOGLE_CLOUD_PROJECT_NAME_BASE)
PROD_GOOGLE_CLOUD_PROJECT_ID     ?= $(PROD_GOOGLE_CLOUD_PROJECT_NAME)-438615
PROD_GOOGLE_CLOUD_PROJECT_NUMBER ?= 378762893981

STAGING_GOOGLE_CLOUD_PROJECT_NAME   ?= $(GOOGLE_CLOUD_PROJECT_NAME_BASE)-staging
STAGING_GOOGLE_CLOUD_PROJECT_ID     ?= $(STAGING_GOOGLE_CLOUD_PROJECT_NAME)-440506
STAGING_GOOGLE_CLOUD_PROJECT_NUMBER ?= 326118600145

ifeq ($(INFRA_ENV),prod)

GOOGLE_CLOUD_PROJECT_NAME   = $(PROD_GOOGLE_CLOUD_PROJECT_NAME)
GOOGLE_CLOUD_PROJECT_ID     = $(PROD_GOOGLE_CLOUD_PROJECT_ID)
GOOGLE_CLOUD_PROJECT_NUMBER = $(PROD_GOOGLE_CLOUD_PROJECT_NUMBER)

GOOGLE_IDP_OAUTH_KEY_SECRET_ID       = $(PROD_GOOGLE_IDP_OAUTH_KEY_SECRET_ID)
GOOGLE_IDP_OAUTH_CLIENT_ID_SECRET_ID = $(PROD_GOOGLE_IDP_OAUTH_CLIENT_ID_SECRET_ID)

else ifeq ($(INFRA_ENV),staging)

GOOGLE_CLOUD_PROJECT_NAME   = $(STAGING_GOOGLE_CLOUD_PROJECT_NAME)
GOOGLE_CLOUD_PROJECT_ID     = $(STAGING_GOOGLE_CLOUD_PROJECT_ID)
GOOGLE_CLOUD_PROJECT_NUMBER = $(STAGING_GOOGLE_CLOUD_PROJECT_NUMBER)

GOOGLE_IDP_OAUTH_KEY_SECRET_ID       = $(STAGING_GOOGLE_IDP_OAUTH_KEY_SECRET_ID)
GOOGLE_IDP_OAUTH_CLIENT_ID_SECRET_ID = $(STAGING_GOOGLE_IDP_OAUTH_CLIENT_ID_SECRET_ID)

else ifeq ($(INFRA_ENV),dev)

GOOGLE_CLOUD_PROJECT_NAME   = $(DEV_GOOGLE_CLOUD_PROJECT_NAME)
GOOGLE_CLOUD_PROJECT_ID     = $(DEV_GOOGLE_CLOUD_PROJECT_ID)
GOOGLE_CLOUD_PROJECT_NUMBER = $(DEV_GOOGLE_CLOUD_PROJECT_NUMBER)

GOOGLE_IDP_OAUTH_KEY_SECRET_ID       = $(DEV_GOOGLE_IDP_OAUTH_KEY_SECRET_ID)
GOOGLE_IDP_OAUTH_CLIENT_ID_SECRET_ID = $(DEV_GOOGLE_IDP_OAUTH_CLIENT_ID_SECRET_ID)

else
  $(error Invalid INFRA_ENV: $(INFRA_ENV))
endif
