name: GCloud Infrastructure Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

concurrency:
  group: gcloud-release
  cancel-in-progress: true

jobs:
  version:
    uses: vegito-app/local/.github/workflows/version-metadata.yml@main
    with:
      environment: prod
      release_bucket_name: vegito-ci-artifacts-${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
    secrets: inherit

  collect-gcp-infos:
    needs: version

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, staging, prod]

    runs-on: self-hosted
    environment: ${{ matrix.environment }}

    env:
      VERSION: ${{ needs.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SA_KEY_GITHUB_ACTIONS_MAIN }}
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

      - name: Collect GCP metadata
        run: |
          make gcloud-config-set-project

          mkdir -p artifacts

          {
            echo "### 🐳 [${{ matrix.environment }}] Docker Repositories"
            echo ""
            make gcloud-docker-repository-public-images-list-public
            echo ""
            make gcloud-docker-repository-private-images-list-private
          } > artifacts/gcloud-${{ matrix.environment }}.md

      - name: Upload metadata to GCS
        run: |
          BUCKET=vegito-ci-artifacts-${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          gcloud storage cp artifacts/gcloud-${{ matrix.environment }}.md \
            gs://${BUCKET}/${GITHUB_REPOSITORY}/${VERSION}/

  release-metadata:
    needs: [version]

    uses: vegito-app/local/.github/workflows/release-metadata.yml@main

    with:
      environment: prod
      version: ${{ needs.version.outputs.version }}
      release_bucket_name: vegito-ci-artifacts-${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

    secrets: inherit

  finalize:
    needs: [release-metadata]

    uses: vegito-app/local/.github/workflows/version-finalize.yml@main

    with:
      environment: prod
      version: ${{ needs.version.outputs.version }}
      release_bucket_name: vegito-ci-artifacts-${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      release_title: "GCloud Infrastructure v${{ needs.version.outputs.version }}"

    secrets: inherit
