name: GCloud Infrastructure Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

concurrency:
  group: gcloud-release
  cancel-in-progress: true

jobs:
  version-changelog:
    uses: vegito-app/local/.github/workflows/version-changelog.yml@v1.19.1
    secrets: inherit

  version-metadata:
    needs: version-changelog
    strategy:
      matrix:
        environment: [dev, staging, prod]
    uses: vegito-app/local/.github/workflows/version-metadata.yml@v1.19.1

    with:
      environment: ${{ matrix.environment }}
      version: ${{ needs.version-changelog.outputs.version }}
      changelog: ${{ needs.version-changelog.outputs.changelog }}

    secrets:
      GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      GOOGLE_CLOUD_SERVICE_ACCOUNT_EMAIL: github-actions-main@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com
      GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER: projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ vars.WORKLOAD_IDENTITY_PROVIDER_ID }}

  collect-gcp-infos:
    needs: version-changelog

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, staging, prod]

    runs-on: self-hosted
    environment: ${{ matrix.environment }}

    env:
      VERSION: ${{ needs.version-changelog.outputs.version }}
      GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER: projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ vars.WORKLOAD_IDENTITY_PROVIDER_ID }}
      GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      GOOGLE_CLOUD_REGION: ${{ secrets.GOOGLE_CLOUD_REGION }}
      INFRA_ENV: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-actions-main@${{ env.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com
          project_id: ${{ env.GOOGLE_CLOUD_PROJECT_ID }}
          token_format: "access_token"
          export_environment_variables: true

      - name: Collect GCP metadata
        run: |
          make gcloud-config-set-project

      - run: |
          mkdir -p artifacts

          OUTPUT=artifacts/RELEASE_BODY.md

          {
            echo "## 🌐 GCloud Infrastructure State"
            echo ""

            echo "### 🐳 Docker Repositories"
            echo ""

            echo "#### Public"
            echo "\`\`\`bash"
            make gcloud-docker-repository-public-images-list
            echo "\`\`\`"
            echo ""

            echo "#### Private"
            echo "\`\`\`bash"
            make gcloud-docker-repository-private-images-list
            echo "\`\`\`"
            echo ""

            echo "### 🌐 Enabled APIs"
            echo ""
            echo "\`\`\`bash"
            make gcloud-services-list-enabled
            echo "\`\`\`"
            echo ""

          } > "$OUTPUT"

      - name: Upload release notes to GCS
        run: |
          BUCKET=vegito-app-${{ env.INFRA_ENV }}-github-actions-ci-artifacts-private
          gs_path=gs://${BUCKET}/${{ github.repository }}/${VERSION}/
          gcloud storage cp artifacts/RELEASE_BODY.md \
            ${gs_path}

  finalize:
    needs: [version-metadata, version-changelog]
    uses: vegito-app/local/.github/workflows/version-finalize.yml@v1.19.1
    with:
      environment: prod
      version: ${{ needs.version-changelog.outputs.version }}
      changelog: ${{ needs.version-changelog.outputs.changelog }}
      release_title: "GCloud Infrastructure Release ${{ needs.version-changelog.outputs.version }}"
      commit_sha: ${{ needs.version-changelog.outputs.commit_sha }}
    secrets:
      GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      GOOGLE_CLOUD_SERVICE_ACCOUNT_EMAIL: github-actions-release-reader@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com
      GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER: projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ vars.WORKLOAD_IDENTITY_PROVIDER_ID }}
