services:
  application-backend:
    build:
      context: ${PWD}
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    image: ${LOCAL_APPLICATION_BACKEND_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/vegito-local:local-application-backend-latest}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-${PWD}/infra/gcloud-credentials.json}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-${GOOGLE_CLOUD_PROJECT_ID}}
      GCLOUD_PROJECT_ID: ${GCLOUD_PROJECT_ID:-${GOOGLE_CLOUD_PROJECT_ID}}
      VEGETABLE_IMAGES_BACKEND_PUBSUB_SUBSCRIPTION: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_VALIDATED_BACKEND_SUBSCRIPTION:-vegetable-images-validated-backend}
      UI_CONFIG_FIREBASE_SECRET_ID: ${UI_CONFIG_FIREBASE_SECRET_ID:-projects/${GOOGLE_CLOUD_PROJECT_ID}/secrets/firebase-config-web/versions/2}
      UI_CONFIG_GOOGLEMAPS_SECRET_ID: ${UI_CONFIG_GOOGLEMAPS_SECRET_ID:-projects/${GOOGLE_CLOUD_PROJECT_ID}/secrets/google-maps-api-key/versions/1}
      VEGETABLE_CREATED_IMAGES_MODERATOR_PUBSUB_TOPIC: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_CREATED_TOPIC:-vegetable-images-created}
      VEGETABLE_VALIDATED_IMAGES_BACKEND_PUBSUB_SUBSCRIPTION: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_VALIDATED_BACKEND_SUBSCRIPTION:-vegetable-images-validated-backend}
      VEGETABLE_VALIDATED_IMAGES_CDN_PREFIX_URL: ${LOCAL_FIREBASE_EMULATORS_VEGETABLE_IMAGES_CDN_PREFIX_URL:-https://vegetable-images-cdn-prefix-url}
      VAULT_ADDR: http://vault-dev:8200
      VAULT_TOKEN: root
    volumes:
      - ${PWD}:${PWD}:cached
    networks:
      dev:
        aliases:
          - application-backend

  application-mobile:
    cap_add:
      - SYS_ADMIN
    image: ${LOCAL_APPLICATION_MOBILE_IMAGE:-${VEGITO_PUBLIC_REPOSITORY}/vegito-local:local-application-mobile-latest}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD}
      APK_PATH: ${LOCAL_ANDROID_APK_PATH:-build/app/outputs/flutter-apk/app-debug.apk}
      DISPLAY_RESOLUTION: "${DISPLAY_RESOLUTION:-1920x1080}"
      DISPLAY: "${DISPLAY:-:20}"
      FLUTTER: flutter
      CHROME_LOG_FILE: /tmp/chrome_debug.log
      LOCAL_ANDROID_STUDIO_LOG_LEVEL: DEBUG
      LOCAL_ANDROID_STUDIO_CONTAINER_CACHE: ${LOCAL_ANDROID_STUDIO_CONTAINER_CACHE:-${PWD}/.containers/android-studio}
      LOCAL_ANDROID_GPU_MODE: ${LOCAL_ANDROID_CONTAINER_GPU_MODE:-swiftshader_indirect}
      LOCAL_APPLICATION_TESTS_MOBILE_IMAGES_DIR: ${LOCAL_APPLICATION_TESTS_MOBILE_IMAGES_DIR:-${PWD}/application/tests/mobile_images}

      LOCAL_ANDROID_AVD_NAME: Pixel_8_Intel
      LOCAL_ANDROID_APK_PATH: mobile/build/app/outputs/flutter-apk/app-release.apk
      LOCAL_ANDROID_APPIUM_EMULATOR_AVD_ON_START: true
      LOCAL_ANDROID_STUDIO_DIR: ${PWD}/local/android/studio
      LOCAL_ANDROID_STUDIO_CACHES_REFRESH: true
      LOCAL_ANDROID_STUDIO_ON_START: true
    privileged: true
    volumes:
      - ${HOST_PWD:-${PWD}}:${PWD}:cached
      - /var/run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    group_add:
      - render
      - kvm
    devices:
      - /dev/kvm
    working_dir: ${PWD}/application/mobile
    command: |
      bash -c '
      set -eu
      sleep infinity
      '
    networks:
      dev:
        aliases:
          - application-mobile
