version: "3.7"
services:
  android-studio:
    tty: true
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    image: ${LOCAL_ANDROID_STUDIO_IMAGE:-${VEGITO_LOCAL_PUBLIC_IMAGES_BASE_NAME:-dbndev/vegito-android}:android-studio-latest}
    env_file:
      - .env
    environment:
      LOCAL_WORKSPACE: ${PWD}
      LOCAL_ANDROID_DEBUG_APK_PATH: ${LOCAL_ANDROID_DEBUG_APK_PATH:-mobile/build/app/outputs/flutter-apk/app-debug.apk}
      DISPLAY_RESOLUTION: "${DISPLAY_RESOLUTION:-1920x1080}"
      DISPLAY: "${DISPLAY:-:20}"
      XPRA_ARGS: ${XPRA_ARGS:-}
      CHROME_LOG_FILE: /tmp/chrome_debug.log
      LOCAL_ANDROID_EMULATOR_AVD_ON_START: ${LOCAL_ANDROID_EMULATOR_AVD_ON_START:-false}
      # LOCAL_ANDROID_EMULATOR_AVD_HEADLESS_ARGS: ${LOCAL_ANDROID_EMULATOR_AVD_HEADLESS_ARGS:-"-no-window"}
      LOCAL_ANDROID_EMULATOR_DATA: ${LOCAL_ANDROID_EMULATOR_DATA:-${PWD}/example-application/tests/mobile_images}
      LOCAL_ANDROID_STUDIO_LOG_LEVEL: DEBUG
      LOCAL_ANDROID_STUDIO_CONTAINER_CACHE: ${LOCAL_ANDROID_STUDIO_CONTAINER_CACHE:-${LOCAL_ANDROID_STUDIO_DIR:-${PWD}/android/studio}/.containers/android-studio}
      LOCAL_ANDROID_STUDIO_CONTAINER_INSTALL: ${LOCAL_ANDROID_STUDIO_CONTAINER_INSTALL:-true}
      LOCAL_ANDROID_STUDIO_ON_START: ${LOCAL_ANDROID_STUDIO_ON_START:-true}
      LOCAL_ANDROID_STUDIO_DIR: ${LOCAL_ANDROID_STUDIO_DIR:-${PWD}/android/studio}

      LOCAL_ANDROID_EMULATOR_AVD_NAME: ${VEGITO_MOBILE_ANDROID_AVD_NAME:-Pixel_8_Intel}
      LOCAL_ANDROID_PACKAGE_NAME: ${VEGITO_MOBILE_ANDROID_PACKAGE_NAME:-dev.vegito.app.android}

      LOCAL_ANDROID_CONTAINER_NAME: ${LOCAL_ANDROID_CONTAINER_NAME:-android-studio}
      LOCAL_ANDROID_CONTAINER_EXEC: ""

    privileged: true
    volumes:
      - ${LOCAL_WORKSPACE:-${PWD}}:${PWD}:cached
    group_add:
      - render
      - ${KVM_GID}
    devices:
      - /dev/kvm
      - /dev/dri
    working_dir: ${LOCAL_ANDROID_STUDIO_DIR:-${PWD}/android/studio}
