services:
  trivy:
    tty: true
    image: ${LOCAL_TRIVY_IMAGE_LATEST:-${VEGITO_PUBLIC_REPOSITORY}/vegito-local:trivy-latest}
    env_file:
      - .env
    environment:
      LOCAL_WORKSPACE: ${PWD}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-vegito-local}
    volumes:
      - ${PWD}:${PWD}:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${PWD}
