# Handle buildx cache in local folder
APPLICATION_IMAGES_MODERATOR_IMAGE = $(IMAGES_BASE):application-images-moderator-$(VERSION)
APPLICATION_IMAGES_MODERATE_IMAGE_DOCKER_BUILDX_LOCAL_CACHE=$(CURDIR)/local/.containers/docker-buildx-cache/application-backend
$(APPLICATION_IMAGES_MODERATOR_IMAGE_DOCKER_BUILDX_LOCAL_CACHE):;	@mkdir -p "$@"
ifneq ($(wildcard $(APPLICATION_IMAGES_MODERATOR_IMAGE_DOCKER_BUILDX_LOCAL_CACHE)/index.json),)
APPLICATION_IMAGES_MODERATOR_IMAGE_DOCKER_BUILDX_LOCAL_CACHE_READ = type=local,src=$(APPLICATION_IMAGES_MODERATOR_IMAGE_DOCKER_BUILDX_LOCAL_CACHE)
endif
APPLICATION_IMAGES_MODERATOR_IMAGE_DOCKER_BUILDX_LOCAL_CACHE_WRITE= type=local,dest=$(APPLICATION_IMAGES_MODERATOR_IMAGE_DOCKER_BUILDX_LOCAL_CACHE)
