services:
  dev:
    tty: true
    image: europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/vegito-local:builder-latest
    env_file:
      - .env
    environment:
      LOCAL_WORKSPACE: ${PWD}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-vegito-local}
    devices:
      - /dev/kvm
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    working_dir: ${PWD}
    volumes:
      - vscode-store:/vscode
      - ${PWD}:${PWD}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
    command: |
      bash -c '
      make docker-sock
      until docker info; do
        echo "Waiting for Docker to be ready..."
        sleep 1
      done
      if [ "$${CODESPACES}" = "true" ] ; then
        echo "Detected '$${CODESPACE_NAME}' Codespaces environment."
        make devcontainer-codespaces
        make local-docker-buildx-setup-github-codespaces
      elif [ "$${MAKE_DEV_ON_START}" = "true" ] ; then
        make devcontainer
      fi
      if [ "$${MAKE_TESTS_ON_START}" = "true" ] ; then
        make application-mobile-wait-for-boot
        make functional-tests
      fi
      sleep infinity
      '
volumes:
  vscode-store:
    external: true
    name: vscode
