name: Build and Push new Version Tag Docker Images To Production registries
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  update-production-images:
    runs-on: self-hosted
    env:
      INFRA_ENV: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Define VERSION
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "build-and-push-images-action@github.com"
          # Bump the version based on commit messages (default patch bump)
          standard-version
          echo "VERSION=$(git describe --tags --abbrev=7 --match 'v*')" >> $GITHUB_ENV
      - name: Use VERSION
        run: echo "Current version is ${{ env.VERSION }}"
      - name: Authenticate to Google Cloud via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/203475703228/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "github-actions-main@moov-dev-439608.iam.gserviceaccount.com"
          project_id: "moov-dev-439608"
          token_format: "access_token"
      - name: Set up Cloud SDK
        run: |
          make gcloud-config-set-project
      - name: Configure Docker for GCR
        run: |
          make gcloud-auth-docker
      - name: Set up Docker Buildx
        run: |
          make docker-buildx-setup
      - name: Bump version and push tags
        run: |
          # Push the new commit and the new tag
          git push --follow-tags origin main
      - name: Build and push up to date project images
        run: |
          make images-ci
