name: Version Prepare (Reusable)
on:
  workflow_call:
    inputs:
      version:
        description: "Precomputed semantic version"
        required: false
        type: string
        default: ""
      changelog:
        description: "Precomputed changelog content"
        required: false
        type: string
        default: ""
      environment:
        description: "Environment"
        required: true
        type: string
      release_bucket_name:
        description: "GCS bucket name for releases"
        required: true
        type: string
      release_bucket_prefix:
        description: "Bucket prefix (usually repository name)"
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      GOOGLE_CLOUD_PROJECT_ID:
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GOOGLE_CLOUD_SA_KEY_GITHUB_ACTIONS_MAIN:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  define_version:
    name: Define VERSION ✨
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SA_KEY_GITHUB_ACTIONS_MAIN }}
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          token_format: "access_token"
          export_environment_variables: true

      - name: Upload New Changes Changelog to GCS
        run: |
          if [ "${{ inputs.changelog }}" != "" ]; then
            GCS_PATH="gs://${{ inputs.release_bucket_name }}/${{ inputs.release_bucket_prefix }}/precomputed-changelog"
            echo "Uploading precomputed changelog to $GCS_PATH"
            echo "${{ inputs.changelog }}" > changelog.md
            gcloud storage cp changelog.md "$GCS_PATH/${GITHUB_RUN_ID}.md"
          else
            echo "No precomputed changelog provided, skipping upload to GCS."
          fi
